# Generated by Django 3.2 on 2023-11-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='raiting',
            new_name='score',
        ),
    ]
