# Generated by Django 3.2 on 2023-11-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reviews',
            new_name='review',
        ),
    ]
