# Generated by Django 3.2 on 2023-11-24 08:35

import api.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user', max_length=20, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('[^m][^e]'), django.core.validators.RegexValidator('^[\\w.@+-]+\\Z'), api.validators.username_me_validator, django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='имя пользователя'),
        ),
    ]
