# Generated by Django 3.2 on 2023-11-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231119_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting',
            name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Текст отзыва'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_title'),
        ),
        migrations.DeleteModel(
            name='Raiting',
        ),
    ]
